import Head from "next/head";
import Carousel from "../components/Carousel";
import Counters from "../components/Counters";
import Offers from "../components/Offers";
import WhatWeOffer from "../components/WhatWeOffer";
import { topSlides, midSlides } from "../components/mocks/allSlides";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="content">
        <Carousel
          numberOfSlides={1}
          sliderClass="top-slider slider"
          slides={topSlides}
          pagination={true}
        />

        <Carousel
          numberOfSlides={1.1}
          sliderClass="mid-slider slider"
          slides={midSlides}
          pagination={false}
        />

        <WhatWeOffer />

        <Offers />

        <Counters />
      </section>
    </div>
  );
}
